apiVersion: v2
appVersion: v3.4.1-2.426.3
type: application
description: An open-source continuous integration server compatible with multiple Source Control Management (SCM) tools, such as CVS, Subversion, and Git. It is capable of executing projects based on Apache Ant and Apache Maven, in addition to running custom scripts.
home: https://jenkins.io/
icon: https://wiki.jenkins.io/JENKINS/attachments/2916393/57409618.png
maintainers:
- email: mohamed.rafraf@kubermatic.com
  name: rafÂ²
- email: mohamedrafraf@insat.u-carthage.tn
  name: mohamed-rafraf
name: kn-jenkins
sources:
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker-agent/
version: 0.0.2